/*
-- Query: SELECT * FROM `class-2014-1-17-610-557-01_jz337`.USER
LIMIT 0, 10000

-- Date: 2014-04-08 16:10
*/
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (1,'nickmyself','123','nickmyself@live.cn','nickmyself');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (2,'aaa','234','aaa@gmail.com','aaa');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (93,'ktt0mb','ktt0mb','eocvzug@eden.gov','qve');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (94,'9b5kv','9b5kv','e8kpdzr@heat.gov','yoc');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (95,'55x94z','55x94z','5qx9p7p@hashtable.org','sx7h');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (96,'c9c7x','c9c7x','8xr3e@zust.com','e3tci');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (97,'c0fk2','c0fk2','0vmeu@rutgers.net','9wnd');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (98,'1hx3q','1hx3q','fas1ujm@google.org','6o6');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (99,'6ak91s','6ak91s','rfvxgdo0@hashtable.gov','m1w');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (100,'0ys19s','0ys19s','mhbr3@blizzard.org','yy6d');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (101,'oj5bat','oj5bat','uq3d3b@hashtable.biz','fl44');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (102,'917na','917na','nah4u@heat.gov','yxyry');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (103,'32sy2j','32sy2j','u708882@rutgers.com','swph');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (104,'deb6x','deb6x','hz62x@eden.org','w0vu');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (105,'sdh8l','sdh8l','hnxja@heat.gov','586x');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (106,'vtoge7','vtoge7','nqfry@linklist.biz','sf7');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (107,'ta6qys','ta6qys','6ttw46d@eden.net','ao1t');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (108,'uzdvw','uzdvw','ic8fv@rutgers.org','r1qo4');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (109,'r3wan','r3wan','zefdnic@heat.net','s4t');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (110,'kl8f22','kl8f22','a37z8d@hotdog.com','3ll54');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (111,'gpfro','gpfro','nt4on2d@heat.net','l57');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (112,'xh2rni','xh2rni','o7s2qn@rutgers.com','g3f');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (113,'keah1h','keah1h','28bpn@rutgers.org','87f');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (114,'oklip','oklip','5cis4b@rutgers.org','l2c0');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (115,'fbxlq7','fbxlq7','73q35zl@zust.net','00ws');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (116,'3ny4a','3ny4a','40r1t8up@zust.com','y6fot');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (117,'yi6mc7','yi6mc7','yjvp2uai@hashtable.biz','i7owr');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (118,'c5np7k','c5np7k','e1tuudv@rutgers.gov','3lt');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (119,'h8ak3','h8ak3','doiatau@hashtable.net','duxz');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (120,'o9iv7i','o9iv7i','mat1ju@eden.com','kje');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (121,'n42di1','n42di1','074hk5@hashtable.gov','1be');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (122,'llnqzi','llnqzi','cr6wi4r@hotdog.biz','pemgg');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (123,'kjrfb','kjrfb','2yooi7nh@google.gov','rikqt');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (124,'f02x6','f02x6','33jhhsfu@eden.biz','zw3a');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (125,'dng3g3','dng3g3','0i29qarw@hashtable.com','vhioi');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (126,'m2of8h','m2of8h','dypdeq@hashtable.org','v0b3');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (127,'9qbli','9qbli','phvcljso@hotdog.gov','o89f9');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (128,'2ep3qy','2ep3qy','b76eig@zust.net','wwuv');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (129,'w0up4','w0up4','06eb7b@hashtable.net','8bkey');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (130,'6zjtp4','6zjtp4','p0rl5t@eden.com','i6rkg');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (131,'w8dmhx','w8dmhx','4mfv4rqn@hotdog.net','zn49t');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (132,'q8x3f','q8x3f','eyukk@zust.com','o101');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (133,'rdvrxc','rdvrxc','sxmz2b@eden.biz','kcly4');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (134,'cqlgc2','cqlgc2','tg9hsz@linklist.com','9u9b5');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (135,'y58eg','y58eg','dtbxzb4@eden.com','i032');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (136,'05yp0','05yp0','zmx25z@zust.net','qv0k3');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (137,'rdwi8k','rdwi8k','s184o@rutgers.com','10dhl');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (138,'4rflu','4rflu','cpdl74j@hotdog.biz','1ja');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (139,'rmh3hz','rmh3hz','pcorrr2@blizzard.org','pmc');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (140,'gvcy8','gvcy8','f01eg4sx@linklist.com','m9q1');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (141,'ms87vx','ms87vx','uosms@eden.org','yhbm');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (142,'ub3ln','ub3ln','5rseids@hashtable.org','1qbpx');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (143,'d2hevt','d2hevt','jjc2n@hotdog.gov','l56');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (144,'cl8s9','cl8s9','qpl0479d@google.biz','a1rl');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (145,'xoo9n','xoo9n','z9eel48i@zust.biz','4ci');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (146,'wuuj88','wuuj88','8g67ka@blizzard.net','if9r9');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (147,'bzwvj5','bzwvj5','rvgxre8s@linklist.gov','mer3');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (148,'ett0f2','ett0f2','h0kno2r@blizzard.com','nl4r3');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (149,'yvmhls','yvmhls','ebfopuh@google.net','77s2o');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (150,'lq9yyl','lq9yyl','7oyd2dx@heat.com','9bus');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (151,'393k8','393k8','7t458s@google.biz','80w');
INSERT INTO `USER` (`UserID`,`UserName`,`Password`,`Email`,`Nickname`) VALUES (152,'w0xhj','w0xhj','2n4bw2@linklist.biz','vqy');
