/*
-- Query: SELECT * FROM `class-2014-1-17-610-557-01_jz337`.RELEASE_COUNTRY
LIMIT 0, 10000

-- Date: 2014-04-08 16:06
*/
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (11,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (12,'Australia');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (12,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (13,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (18,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (22,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (58,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (78,'Hong Kong');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (78,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (78,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (82,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (85,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (89,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (98,'Malta');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (98,'Morocco');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (98,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (98,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (105,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (115,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (115,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (120,'New Zealand');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (120,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (121,'New Zealand');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (121,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (122,'New Zealand');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (122,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (129,'Japan');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (152,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (154,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (155,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (155,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (161,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (200,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (218,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (218,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (238,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (240,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (241,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (242,'Italy');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (242,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (272,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (272,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (277,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (277,'Hungary');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (277,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (277,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (278,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (280,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (280,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (285,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (296,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (296,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (296,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (329,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (330,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (331,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (348,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (348,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (425,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (453,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (500,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (510,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (534,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (534,'Italy');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (534,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (534,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (550,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (550,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (557,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (558,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (559,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (562,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (597,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (603,'Australia');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (603,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (646,'Jamaica');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (646,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (671,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (671,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (679,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (679,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (680,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (755,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (767,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (767,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (769,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (808,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (809,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (812,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (834,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (840,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (857,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (862,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (920,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (950,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (953,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1103,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1103,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1124,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1248,'Czech Republic');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1248,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1248,'Italy');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1248,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1271,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1417,'Mexico');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1417,'Spain');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1422,'Hong Kong');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1422,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1487,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1571,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1572,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1573,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1576,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1577,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1577,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1577,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1577,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1588,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1593,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1593,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1724,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1726,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1734,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1735,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1735,'China');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1735,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1735,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1771,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1830,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1830,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1830,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1858,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1865,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1891,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1892,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1893,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1894,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1895,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1930,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1965,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1992,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1995,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1996,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1996,'Japan');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1996,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (1996,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2062,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2080,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2105,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2493,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2501,'Czech Republic');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2501,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2501,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2502,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2502,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2503,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2503,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2649,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2770,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2787,'Australia');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (2789,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (3071,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (3511,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (3511,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (4133,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (4538,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (4638,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (5689,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (7443,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (7737,'Australia');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (7737,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (7737,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (7737,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (7737,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8054,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8054,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8054,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8273,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8274,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8275,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8277,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8355,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8373,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8409,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8587,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8681,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8681,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8681,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8698,'Czech Republic');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8698,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8698,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8698,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8871,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (8871,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9257,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9339,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9361,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9381,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9381,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9473,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9506,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9543,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9615,'Japan');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9615,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9762,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9799,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9839,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9839,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9902,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (9902,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (10138,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (10191,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (10192,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (10193,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (10195,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (10196,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (10307,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (10328,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (10527,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (10681,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (10764,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (10764,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (11238,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (11322,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (11324,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (11430,'Australia');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (11430,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (11452,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (11619,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (11619,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (11824,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (12105,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (12192,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (12437,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (12444,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (12444,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (12445,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (12573,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (12573,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (12573,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (13053,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (13179,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (13475,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (13475,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (13804,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (13995,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (14160,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (14161,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (14161,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (14756,'Hong Kong');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (14869,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (15357,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (15512,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (16164,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (16577,'Hong Kong');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (16577,'Japan');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (16577,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (16710,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (16781,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (16869,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (16869,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (18823,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (19913,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (19995,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (19995,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (20352,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (20504,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (20526,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (20676,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (21385,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (24021,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (24253,'Sweden');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (24428,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (25475,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (26123,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (26367,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (26963,'Belgium');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (26963,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (26963,'Ireland');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (27205,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (27578,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (32261,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (34673,'Sweden');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (35791,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (35791,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (35791,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (36557,'Czech Republic');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (36557,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (36557,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (36557,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (36657,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (36658,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (36668,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (36668,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (36668,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (36669,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (36669,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (37165,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (37233,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (37632,'Aruba');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (37632,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (37724,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (37724,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (38055,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (38356,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (38365,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (39514,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (39514,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (39928,'Spain');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (41154,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (41283,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (41602,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (42189,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (44683,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (44833,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (44896,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (46195,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (47964,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49013,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49026,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49040,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49047,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49047,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49051,'New Zealand');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49051,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49519,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49521,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49521,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49521,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49524,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49529,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (49538,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (50444,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (50546,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (50619,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (51017,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (51497,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (52520,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (53182,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (54138,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (54441,'Italy');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (56292,'United Arab Emirates');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (56292,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (57158,'New Zealand');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (57158,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (57165,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (57201,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (57800,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (58244,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (58244,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (58244,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (58574,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (59951,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (59962,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (59967,'China');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (59967,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (62177,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (62211,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (64635,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (64635,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (64682,'Australia');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (64682,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (64686,'Hungary');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (64686,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (64686,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (64807,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (65291,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (68718,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (68721,'China');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (68721,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (68724,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (68726,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (68726,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (68728,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (68734,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (70160,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (70981,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (70981,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (71552,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (71676,'United Arab Emirates');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (71676,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (71679,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (71679,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (72190,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (72190,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (72331,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (72559,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (72710,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (74461,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (74510,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (75258,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (75612,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (75656,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (75656,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (75780,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (76101,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (76163,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (76170,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (76203,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (76285,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (76338,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (76492,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (76589,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (76640,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (77338,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (77663,'Belgium');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (77663,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (77931,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (77950,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (77951,'Australia');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (77951,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (77951,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (78383,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (79067,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (80274,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (80321,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (81005,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (81452,'Japan');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (82675,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (82684,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (82690,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (82693,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (82700,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (82992,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (83542,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (83542,'Hong Kong');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (83542,'Singapore');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (83542,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (85446,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (85889,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (86130,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (86331,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (86829,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (86829,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (86829,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (86834,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (87101,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (87421,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (87502,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (87516,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (87827,'Taiwan');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (87827,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (87827,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (91314,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (91586,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (93456,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (96721,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (96721,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (96721,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (97020,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (97630,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (100241,'Australia');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (100241,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (100402,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (100542,'Malaysia');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (101286,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (101299,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (106646,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (107846,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (107985,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (109091,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (109417,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (109424,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (109439,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (109443,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (109445,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (109451,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (110414,'Belgium');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (110414,'Denmark');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (110414,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (110414,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (110415,'Czech Republic');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (110415,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (110415,'Korea, Republic of');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (110415,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (111473,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (112205,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (112205,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (115283,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (115782,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (116711,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (116741,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (116745,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (117251,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (117263,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (119283,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (119892,'China');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (121640,'Israel');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (121640,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (121734,'Spain');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (122906,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (123553,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (124905,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (125509,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (126250,'Denmark');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (126250,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (126250,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (126250,'Italy');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (126250,'Sweden');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (127585,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (129670,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (132344,'Greece');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (132344,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (132363,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (133805,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (134374,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (135397,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (136400,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (136418,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (136418,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (136795,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (137093,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (137106,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (137321,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (138697,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (138832,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (138843,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (140823,'Australia');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (140823,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (140823,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (146216,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (146223,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (146223,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (146233,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (146238,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (146239,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (146243,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (146381,'Spain');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (151960,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (152532,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (152601,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (152737,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (152742,'Italy');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (155084,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (156717,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (157099,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (157350,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (160139,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (160139,'Portugal');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (160139,'Switzerland');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (160588,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (162903,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (164457,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (168672,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (169298,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (169881,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (171759,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (171776,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (172385,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (172391,'South Africa');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (172631,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (173897,'Australia');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (173897,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (173897,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (174378,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (174378,'Ireland');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (175112,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (175291,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (175555,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (175574,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (177494,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (181009,'China');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (181009,'Hong Kong');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (187010,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (188207,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (190955,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (190955,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (192136,'South Africa');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (192136,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (193756,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (199373,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (201066,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (202214,'Portugal');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (203833,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (204082,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (205220,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (205724,'Puerto Rico');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (205724,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (205724,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (207323,'Denmark');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (208134,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (209247,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (209263,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (209406,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (210047,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (211449,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (214140,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (217316,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (217993,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (225747,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (227348,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (227783,'Canada');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (227783,'Korea, Republic of');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (230222,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (230896,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (240916,'Italy');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (240916,'Kuwait');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (240916,'Netherlands');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (240916,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (242042,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (242076,'Bahamas');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (242076,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (244688,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (248268,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (249397,'Belgium');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (249397,'Denmark');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (249397,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (249397,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (249397,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (253046,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (254263,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (255491,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (255718,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (256731,'United States of America');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (258216,'Belgium');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (258216,'Denmark');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (258216,'France');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (258216,'Germany');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (258216,'United Kingdom');
INSERT INTO `RELEASE_COUNTRY` (`MOVIE_MovieID`,`Country`) VALUES (260203,'New Zealand');
